Update patch set 1
Patch Set 1:

I'm sorry if I'm missing something, but for me on M7 this breaks the build. I tried a clean build and got the error shown below. I uncommented the 2 lines from this change and did another clean build and it worked fine. Of course I am cherry picking Hector's 3 open M7 patches including kernel 3.4.92...

using device-specific extensions in device/htc/common
unable to load device-specific module; assuming none
building image from target_files BOOT...
  running:  mkbootfs -f /tmp/targetfiles-z5tnFb/META/boot_filesystem_config.txt /tmp/targetfiles-z5tnFb/BOOT/RAMDISK
  running:  minigzip
  running:  mkbootimg --kernel /tmp/targetfiles-z5tnFb/BOOT/kernel --cmdline console=ttyHSL0,115200,n8 androidboot.hardware=qcom user_debug=31 --base 0x80600000 --pagesize 2048 --ramdisk_offset 0x01800000 --ramdisk /tmp/tmp_sy0S0 --output /tmp/tmpP_1uuX
Traceback (most recent call last):
  File "./build/tools/releasetools/ota_from_target_files", line 1148, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/ota_from_target_files", line 1116, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "./build/tools/releasetools/ota_from_target_files", line 570, in WriteFullOTAPackage
    MakeRecoveryPatch(OPTIONS.input_tmp, output_zip, recovery_img, boot_img)
NameError: global name 'recovery_img' is not defined
make: *** [/home/chezbel/android/aicp44/out/target/product/m7/aicp_m7-ota-eng.chezbel.zip] Error 1

Patch-set: 1
Reviewer: Gerrit User 10 <10@9f904cbb-a964-4fab-a7dc-5cfc4d5c238b>
Label: Code-Review=0