Build: Remove ro.product.model from flash info
This breaks unified devices

   ERROR: couldn't find ro.product.model in build.prop

Change-Id: If101f31042fbe7a486435e9f7878c3773b6ccb15